import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from './../components/Header';
import Profile from './../components/Profile';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Rachel's Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<section id="profile">
				<Profile />
			</section>
		</div>
	);
}
