import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from './../components/Header';
import Profile from './../components/Profile';
import Skill from './../components/Skill';
import Experience from './../components/Experience';
import About from './../components/About';

export default function Home() {
	return (
		<div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0 ">
			<Head>
				<title>Rachel's Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<section id="profile" className="snap-center">
				<Profile />
			</section>

			<section id="about" className="snap-center">
				<About />
			</section>

			<section id="skill" className="snap-center">
				<Skill />
			</section>

			<section id="exprience" className="snap-center">
				<Experience />
			</section>
		</div>
	);
}
